### ISSUE TITLE
Documentation bug: Invalid Discord link in blog page

### ISSUE THREAD

**Issue by philipmather** [frenspage/frenspage#7]
On the page https://mirror.xyz/0x390147288E480B1457E49CA174bB9f2290B88dbB/dsBnxmNXPftD8SoLhn_Ntt1lAhmMJ4AXZVoiSyHXzB0 the link in...

`If you want to join the dev team and help us buidl, feel free to ask for a dev role in the frens Discord.`

...the Discord link is invalid.

**Comment by mitchoz** [comment]
Thx!
Updated
